import logging
from collections.abc import AsyncIterable
from typing import Any, Literal


from common import prompts
from common.base_agent import BaseAgent
from common.types import TaskList
from common.utils import init_api_key
from langchain_core.messages import AIMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.checkpoint.memory import MemorySaver
from langchain.agents import create_agent
from pydantic import BaseModel, Field

memory = MemorySaver()

logger = logging.getLogger(__name__)

class ResponseFormat(BaseModel):
     """Respond to the user in this format."""

     status: Literal['input_required', 'completed', 'error'] = Field(description="""The status of the agent's response.
                         'input_required' indicates that the agent needs more information from the user to proceed.
                         'completed' indicates that the agent has completed its task and has a final response.
                         'error' indicates that an error occurred during the agent's processing.""",
                         default='input_required')
     question: str | dict = Field(description="Input needed from the user to generate the plan")
     content: TaskList = Field(
                    description= """List of tasks generated by the PlannerAgent to be executed sequentially.
                    Each task includes a description of the task, the agent responsible for executing it,
                    and any relevant parameters or information needed for execution.   """
               )

class PlannerAgent(BaseAgent):
     """The PlannerAgent is responsible for generating a sequential plan of tasks based on a user's query.
     It uses a language model to analyze the query, extract relevant information, and create a structured plan
     that can be executed by other agents in the system. The PlannerAgent ensures that the generated tasks are coherent,
     actionable, and aligned with the user's goals.  The Planner Agent is backed by Langgraph"""

     def __init__(self):
          init_api_key()

          logger.info("Initializing Planner Agent")

          super().__init__(
               agent_name="PlannerAgent",
               description="An agent that generates a sequential plan of tasks based on a user's query.",
               content_types=['text', 'text/plain']
          )

          self.model = ChatGoogleGenerativeAI(
               model="gemini-2.0-flash",
               temperature=0.2, max_tokens=10000
               )

          self.graph = create_agent(
               llm=self.model,
               agent_name=self.agent_name,
               description=self.description,
               memory=memory,
               response_format=ResponseFormat,
               system_message=prompts.PLANNER_AGENT_COT_PROMPT
          )

     def invoke(self, query:str, sessionId:str, task_id:str) -> AsyncIterable[dict[str, Any]]:
          """Invoke the PlannerAgent with the user's query and return an asynchronous stream of responses containing the generated plan of tasks."""

          logger.info(f"Invoking Planner Agent with query: \n{query}, \nsessionId: {sessionId}, \ttask_id: {task_id}")
          config = {'configurable': {'thread_id': sessionId}}
          self.graph.invoke({'messages': [('user', query)]}, config=config)
          return self.get_agent_response(config)

     async def stream(
          self, query: str, sessionId: str, task_id: str
     ) -> AsyncIterable[dict[str, Any]]:
          """Stream the PlannerAgent's response as it generates the plan of tasks,
          yielding updates in real-time as they become available."""
          inputs = {'messages': [('user', query)]}
          config = {'configurable': {'thread_id': sessionId}}

          logger.info(
               f"Streaming response from Planner Agent with query: \n{query}, \nsessionId: {sessionId}, \ttask_id: {task_id}"
          )
          for item in self.graph.stream(inputs, config, stream_mode='values'):
               logger.debug(f"Received item from Planner Agent stream: \n{item}\n\n")
               message = item['message'][-1]
               if isinstance(message, AIMessage):
                    yield {
                         'response_type': 'text',
                         'is_task_complete': False,
                         'require_user_input': False,
                         'content': message.content
                         }
          yield self.get_agent_response(config)
     def get_agent_response(self, config) -> dict[str, Any]:
          """Retrieves the final response from the PlannerAgent after processing the user's query,
          including the generated plan of tasks and any relevant status information."""
          current_state = self.graph.get_state(config)
          structured_response = current_state.values.get('structured_response')

          if structured_response and isinstance(structured_response, ResponseFormat):
               if (structured_response.status == 'input_required'):
                    return {
                         'response_type': 'text',
                         'is_task_complete': False,
                         'require_user_input': True,
                         'content': structured_response.question
                    }
               elif (structured_response.status == 'completed'):
                    return {
                         'response_type': 'data',
                         'is_task_complete': True,
                         'require_user_input': False,
                         'content': structured_response.content.model_dump()
                    }
               elif (structured_response.status == 'error'):
                    return {
                         'response_type': 'text',
                         'is_task_complete': True,
                         'require_user_input': False,
                         'content': structured_response.question
                    }
          return {
               'is_task_complete': False,
               'require_user_input': True,
               'content': "The planner agent did not return a valid response. Please provide more information or rephrase your query."
          }