# =============================================================================
# Unit Tests: src/common/types.py
# =============================================================================
# Pure-Pydantic unit tests — no cloud services or database connections required.
# These validate model instantiation, field defaults, enum values, and JSON
# serialization for all shared data types used by agents and tools.
#
# Run with:
#   poetry run pytest src/common/test_types.py -v
# =============================================================================

import json
import pytest
from datetime import datetime

from src.common.types import (
    AgentResponse,
    DeliverableStatus,
    ImageUrlInput,
    LinkMetadata,
    PlannerResponseFormat,
    PlannerTask,
    ScrapeAndPushArgs,
    ServerConfig,
    TaskList,
)


# ── ServerConfig ────────────────────────────────────────────────────────────

class TestServerConfig:
    """Configuration for agent/MCP server binding."""

    def test_defaults(self):
        """Default host is localhost, port 10101, transport streamable-http."""
        cfg = ServerConfig()
        assert cfg.host == "localhost"
        assert cfg.port == 10101
        assert cfg.transport == "streamable-http"
        assert cfg.path == "/mcp"

    def test_custom_port(self):
        """Port can be overridden for each agent's dedicated port."""
        cfg = ServerConfig(port=10115, path="/agents/mcp")
        assert cfg.port == 10115
        assert cfg.path == "/agents/mcp"

    def test_model_dump(self):
        """Serializes to a plain dict for MCP tool returns."""
        cfg = ServerConfig(host="0.0.0.0", port=8000)
        d = cfg.model_dump()
        assert d["host"] == "0.0.0.0"
        assert d["port"] == 8000


# ── PlannerTask ─────────────────────────────────────────────────────────────

class TestPlannerTask:
    """A single task generated by the PlannerAgent in a task list."""

    def test_minimal(self):
        """Only id and description are required."""
        task = PlannerTask(id=1, description="Research AI trends")
        assert task.id == 1
        assert task.description == "Research AI trends"
        assert task.status == "input_required"  # default
        assert task.research_project_id is None

    def test_with_project(self):
        """research_project_id tracks which campaign a task belongs to."""
        task = PlannerTask(
            id=2,
            description="Write blog post",
            research_project_id="abc-123",
        )
        assert task.research_project_id == "abc-123"

    def test_status_values(self):
        """All documented status literals are accepted."""
        for status in [
            "input_required",
            "completed",
            "error",
            "pending",
            "incomplete",
            "todo",
            "not_started",
        ]:
            task = PlannerTask(id=0, description="test", status=status)
            assert task.status == status

    def test_any_status_accepted(self):
        """The status field includes Any in its union, so any string is accepted.
        This reflects the PlannerTask schema in src/common/types.py."""
        task = PlannerTask(id=0, description="test", status="bogus_status")
        assert task.status == "bogus_status"


# ── TaskList ────────────────────────────────────────────────────────────────

class TestTaskList:
    """A collection of tasks generated by the PlannerAgent."""

    def test_default_empty(self):
        """tasks defaults to an empty list."""
        tl = TaskList()
        assert tl.tasks == []
        assert tl.original_query is None
        assert tl.research_project_id is None
        assert tl.research_context is None

    def test_with_tasks(self):
        """Can hold a sequenced list of PlannerTasks."""
        tasks = [
            PlannerTask(id=1, description="Step 1"),
            PlannerTask(id=2, description="Step 2"),
        ]
        tl = TaskList(
            original_query="Create marketing campaign",
            research_project_id="proj-456",
            tasks=tasks,
        )
        assert len(tl.tasks) == 2
        assert tl.tasks[0].id == 1
        assert tl.tasks[1].description == "Step 2"
        assert tl.original_query == "Create marketing campaign"

    def test_model_dump_serializable(self):
        """model_dump() produces JSON-compatible output."""
        tl = TaskList(
            original_query="Test",
            tasks=[PlannerTask(id=1, description="Do something")],
        )
        d = tl.model_dump()
        assert isinstance(d["tasks"], list)
        assert d["tasks"][0]["description"] == "Do something"
        json.dumps(d)  # must not raise


# ── PlannerResponseFormat ───────────────────────────────────────────────────

class TestPlannerResponseFormat:
    """Structured response from the PlannerAgent."""

    def test_input_required(self):
        """When the planner needs more info, status='input_required' and
        question field holds the prompt."""
        resp = PlannerResponseFormat(
            status="input_required",
            question="What topic should I research?",
        )
        assert resp.status == "input_required"
        assert resp.question == "What topic should I research?"
        assert len(resp.content.tasks) == 0

    def test_completed_with_tasks(self):
        """On success, status='completed' and content holds the TaskList."""
        tasks = TaskList(
            original_query="Help with marketing",
            tasks=[PlannerTask(id=1, description="Analyze market")],
        )
        resp = PlannerResponseFormat(status="completed", content=tasks)
        assert resp.status == "completed"
        assert resp.question == ""  # default
        assert len(resp.content.tasks) == 1

    def test_error_status(self):
        """Error status with a question/message describing the error."""
        resp = PlannerResponseFormat(
            status="error",
            question="Failed to parse the query. Please rephrase.",
        )
        assert resp.status == "error"

    def test_model_dump_serializable(self):
        """Full object tree serializes to JSON."""
        resp = PlannerResponseFormat(
            status="completed",
            content=TaskList(
                original_query="Test",
                tasks=[PlannerTask(id=1, description="Step")],
            ),
        )
        d = resp.model_dump()
        assert d["status"] == "completed"
        assert d["content"]["original_query"] == "Test"
        json.dumps(d)  # must not raise


# ── AgentResponse ───────────────────────────────────────────────────────────

class TestAgentResponse:
    """Generic output schema for any agent's response."""

    def test_string_content(self):
        """Content can be a plain string."""
        resp = AgentResponse(
            content="Task completed successfully.",
            is_task_complete=True,
            require_user_input=False,
        )
        assert resp.content == "Task completed successfully."
        assert resp.is_task_complete is True
        assert resp.require_user_input is False

    def test_dict_content(self):
        """Content can be a structured dict."""
        resp = AgentResponse(
            content={"summary": "Done", "items": 3},
            is_task_complete=True,
            require_user_input=False,
        )
        assert resp.content["summary"] == "Done"

    def test_requires_input(self):
        """When the agent needs more info, flags are set accordingly."""
        resp = AgentResponse(
            content="What budget do you have?",
            is_task_complete=False,
            require_user_input=True,
        )
        assert resp.require_user_input is True
        assert resp.is_task_complete is False

    def test_model_dump(self):
        """Serializes for A2A artifact transport."""
        resp = AgentResponse(
            content="Done",
            is_task_complete=True,
            require_user_input=False,
        )
        d = resp.model_dump()
        assert d["is_task_complete"] is True
        assert not d["require_user_input"]


# ── DeliverableStatus ───────────────────────────────────────────────────────

class TestDeliverableStatus:
    """Tracks lifecycle state of a deliverable (report, blog, image, etc.)."""

    def test_default(self):
        """New deliverables start as 'not_started'."""
        ds = DeliverableStatus()
        assert ds.status == "not_started"

    def test_all_statuses_accepted(self):
        """All documented lifecycle states are valid."""
        valid = [
            "not_started",
            "in_progress",
            "waiting_for_review",
            "needs_revision",
            "approved",
            "rejected",
            "cancelled",
            "completed",
        ]
        for s in valid:
            ds = DeliverableStatus(status=s)
            assert ds.status == s


# ── LinkMetadata ────────────────────────────────────────────────────────────

class TestLinkMetadata:
    """Metadata for a web link to be scraped and indexed."""

    def test_all_fields(self):
        """title, author, date, and source are all required."""
        lm = LinkMetadata(
            title="AI in Marketing 2025",
            author="Jane Doe",
            date="2025-03-15",
            source="https://example.com/ai-marketing",
        )
        assert lm.title == "AI in Marketing 2025"
        assert lm.author == "Jane Doe"
        assert lm.source.startswith("https://")

    def test_model_dump(self):
        """Serializes for PineconeScrapeAndPush payloads."""
        lm = LinkMetadata(
            title="Test", author="A", date="2025-01-01", source="https://x.com"
        )
        d = lm.model_dump()
        assert d["title"] == "Test"
        assert d["source"] == "https://x.com"


# ── ScrapeAndPushArgs ───────────────────────────────────────────────────────

class TestScrapeAndPushArgs:
    """Arguments for the Pinecone scrape-and-push tool."""

    def test_single_url(self):
        """Maps one URL to its metadata."""
        args = ScrapeAndPushArgs(
            result_dict={
                "https://example.com": LinkMetadata(
                    title="Page", author="A", date="2025-01-01", source="example.com"
                )
            }
        )
        assert "https://example.com" in args.result_dict

    def test_multiple_urls(self):
        """Can batch multiple URLs in one call."""
        args = ScrapeAndPushArgs(
            result_dict={
                "https://a.com": LinkMetadata(
                    title="A", author="a", date="1", source="a.com"
                ),
                "https://b.com": LinkMetadata(
                    title="B", author="b", date="2", source="b.com"
                ),
            }
        )
        assert len(args.result_dict) == 2


# ── ImageUrlInput ───────────────────────────────────────────────────────────

class TestImageUrlInput:
    """Input for the tiny-URL generation tool."""

    def test_long_url(self):
        """Accepts the long S3 URL and returns a shortened one."""
        inp = ImageUrlInput(image_url="https://s3.amazonaws.com/bucket/long/path/img.png")
        assert inp.image_url.startswith("https://")

    def test_model_dump(self):
        """Serializes cleanly for tool calls."""
        inp = ImageUrlInput(image_url="https://example.com/img.png")
        d = inp.model_dump()
        assert d["image_url"] == "https://example.com/img.png"
