from langchain_core.documents import Document
from typing import Any, List, Literal, Optional
from pydantic import BaseModel, Field, model_validator
from sqlalchemy import values

class ServerConfig(BaseModel):
     host: str = Field(default="localhost", description="The host to run the server on")
     port: int = Field(default=10101, description="The port to run the server on")
     transport: str = Field(default="streamable-http", description="The transport protocol to use (streamable-http, sse, stdio)")
     path: str = Field(default="/mcp", description="URL path the MCP server is mounted at (e.g. /mcp, /tools/mcp, /agents/mcp)")


class PlannerTask(BaseModel):
     """Represents a single task generated by the PlannerAgent."""

     id: int = Field(description="Unique identifier for the task")
     description: str = Field(description="A brief and clear description of the task to be executed.")
     research_project_id: Optional[str] = Field(default=None, description="The research_project_id for this campaign, passed from the Marketing Assistant Agent")
     status: (Any | Literal[
          'input_required',
          'completed',
          'error',
          'pending',
          'incomplete',
          'todo',
          'not_started'] | None) = Field(description="Current status of the task.", default='input_required')


class DeliverableStatus(BaseModel):
     status: (Any | Literal[
          'not_started',
          'in_progress',
          'waiting_for_review',
          'needs_revision',
          'approved',
          'rejected',
          'cancelled',
          'completed',
          ] | None) = Field(description="Current status of the deliverable.", default='not_started')
     # @model_validator(mode='before')
     # @classmethod
     # def set_depenedent_var(cls, values):
     #      """Pydantic dependent setters"""
     #      if isinstance(values, dict) and 'start_date' in values:
     #           values['checkin_date'] = values['start_date']

     #      if isinstance(values, dict) and 'end_date' in values:
     #           values['checkout_date'] = values['end_date']

     #      if isinstance(values, dict) and 'start_date' in values:
     #           values['car_rental_start_date'] = values['start_date']

     #      if isinstance(values, dict) and 'end_date' in values:
     #           values['car_rental_end_date'] = values['end_date']

     #      return values




class TaskList(BaseModel):
     """A list of tasks generated by the PlannerAgent."""
     original_query: str | None = Field(default=None,
          description='The original user query for context.'
     )
     research_project_id: Optional[str] = Field(default=None, description="The research_project_id for this campaign, passed from the Marketing Assistant Agent")
     research_context: str | None = Field(default=None,
          description='Contextual information or research project related to the tasks.'
     )
     tasks: list[PlannerTask] = Field(default_factory=list, description="List of tasks to be executed sequentially.")


class PlannerResponseFormat(BaseModel):
     """Structured response format for the PlannerAgent."""
     research_project_id: Optional[str] = Field(default=None, description="The research_project_id for this campaign, passed from the Marketing Assistant Agent")
     status: Literal['input_required', 'completed', 'error'] = Field(
          description=(
               "The status of the agent's response. "
               "'input_required' indicates that the agent needs more information from the user to proceed. "
               "'completed' indicates that the agent has completed its task and has a final response. "
               "'error' indicates that an error occurred during the agent's processing."
          ),
          default='input_required',
     )
     question: str | dict = Field(default='', description="Input needed from the user to generate the plan")
     content: TaskList = Field(
          default_factory=TaskList,
          description=(
               "List of tasks generated by the PlannerAgent to be executed sequentially. "
               "Each task includes a description of the task, the agent responsible for executing it, "
               "and any relevant parameters or information needed for execution."
          )
     )


class AgentResponse(BaseModel):
     """Output schema for the Agent"""
     content: str | dict = Field(description="The content of the agent's response, which can be a string or a structured dictionary depending on the context.")
     is_task_complete: bool = Field(description="Indicates whether the task associated with this response is complete.")
     require_user_input: bool = Field(description="Indicates whether the agent requires additional input from the user to proceed with task execution.")
class LinkMetadata(BaseModel):
     title: str
     author: str
     date: str
     source: str

class ScrapeAndPushArgs(BaseModel):
     result_dict: dict[str, LinkMetadata] = Field(
          description="Mapping of URL to its metadata (title, author, date, source) for each link to scrape and index."
     )


class ImageSaverS3Args(BaseModel):
     image_url: str = Field(description="The URL of the image to be saved.")
     s3_bucket_name: str = Field(description="The name of the S3 bucket where the image should be saved.")
     s3_object_key: str = Field(description="The object key (path) in the S3 bucket where the image should be saved.")

class ImageUrlInput(BaseModel):
     image_url: str = Field(description="Long Image URL provided for a tool which returns a tiny URL")


class PineconeResults(BaseModel):
     serialized: str | None = Field (default_factory=None, description="The serialized results of the query")
     retrieved_docs: List[Document] | None= Field (default_factory=None, description="The retrieved documents")
