from typing import Any, Literal
from pydantic import BaseModel, Field, model_validator
from sqlalchemy import values

class ServerConfig(BaseModel):
     host: str = Field(default="localhost", description="The host to run the server on")
     port: int = Field(default=10101, description="The port to run the server on")
     transport:str = Field(default="http", description="The transport protocol to use (e.g. http, grpc)")


class PlannerTask(BaseModel):
     """Represents a single task generated by the PlannerAgent."""

     id: int = Field(description="Unique identifier for the task")
     description: str = Field(description="A brief and clear description of the task to be executed.")
     status: (Any | Literal[
          'input_required',
          'completed',
          'error',
          'pending',
          'incomplete',
          'todo',
          'not_started'] | None) = Field(description="Current status of the task.", default='input_required')

class TripInfo(BaseModel):
     """Trip Information"""
     total_budget:str | None = Field(description="Total budget for the trip")
     origin:str | None = Field(description="Origin of the trip")
     destiination: str | None = Field(description="Destination of the trip")
     type : (Any | Literal['leisure', 'business'] | None) = Field(description="Type of the trip (leisure or business)")
     start_date: str | None = Field (description="Start date of the trip")
     end_date: str | None = Field(description="End date of the trip")
     travel_class: (Any | Literal['first', 'business', 'economy'] | None) = Field(description="Travel class (e.g. economy, business, first)")
     accommodation_type: (Any | Literal['Luxury Hotel', 'Budget Hotel', 'Hostel', 'airBnB'] | None) = Field(description="""
                                                                                                         Preferred accommodation type, luxury hotel, budget hotel, hostel, airBnB, etc.""")
     room_type : (Any | Literal['single', 'double', 'suite'] | None) = Field(description="Preferred room type (e.g. single, double, suite, or etc.)")
     type_of_car: (Any | Literal['SUV', 'sedan', 'Truck', 'minivan'] | None) = Field(description="Preferred type of rental car (e.g. SUV, sedan, truck, minivan, etc.)")
     is_car_rental_required: str | None = Field(description="Indicates whether car rental is required (true or false) for the trip")
     no_of_travellers: str | None = Field(description="Number of travelers for the trip")
     checkin_date :str | None = Field(description="Check-in date for the accommodation")
     checkout_date : str | None = Field(description="Check-out date for the accommodation")
     car_rental_start_date: str | None = Field(description="Start date for car rental")
     car_rental_end_date: str | None = Field(description="End date for car rental")

     @model_validator(mode='before')
     @classmethod
     def set_depenedent_var(cls, values):
          """Pydantic dependent setters"""
          if isinstance(values, dict) and 'start_date' in values:
               values['checkin_date'] = values['start_date']

          if isinstance(values, dict) and 'end_date' in values:
               values['checkout_date'] = values['end_date']

          if isinstance(values, dict) and 'start_date' in values:
               values['car_rental_start_date'] = values['start_date']

          if isinstance(values, dict) and 'end_date' in values:
               values['car_rental_end_date'] = values['end_date']

          return values


class TaskList(BaseModel):
     """Output schema for the Planner Agent."""
     original_query: str | None = Field(description="The original user query that was provided to the PlannerAgent")
     trip_info: TripInfo | None = Field(description="Trip Information")
     tasks: list[PlannerTask] = Field(description="List of tasks generated by the PlannerAgent to be executed sequentially")


class AgentResponse(BaseModel):
     """Output schema for the Agent"""
     content: str | dict = Field(description="The content of the agent's response, which can be a string or a structured dictionary depending on the context.")
     is_task_complete: bool = Field(description="Indicates whether the task associated with this response is complete.")
     require_user_input: bool = Field(description="Indicates whether the agent requires additional input from the user to proceed with task execution.")